### ISSUE TITLE
JRubyを用いてRuby処理系なしでもUniNodeクラス群を生成できるようにする

### ISSUE THREAD

**Issue by exKAZUu** [UnicoenProject/Junicoen#13]
~~加えてリポジトリを分ける。~~

**Comment by irxground** [comment]
リポジトリを分けるのであればむしろ Rubyのままでよいのでは？
将来的なことを考えると、Rubyで書いたDSLからJavaScriptのクラスを生成することも考えられるんですよね？

**Comment by exKAZUu** [comment]
Rubyの開発環境を手元においておくのが面倒なのよ・・・
あと、リポジトリを分けることと、JRuby使うかどうかは無関係だと思うが如何？

**Comment by irxground** [comment]
- Javaと協調動作するからJRubyを使う→わかる
- RubyのリポジトリだけどJRubyのインストールスクリプトなんかが含まれてる→変では？

という感じです

**Comment by exKAZUu** [comment]
なんでも良いんだが、開発環境なしでさくっと動かせる方法ないだろか？
いっそWebアプリとかにした方がいいんだろか？

**Comment by exKAZUu** [comment]
JRubyを導入して、 #14 という構成を取ることに決めた
