### ISSUE TITLE
.g4ファイル追加時のエラー

### ISSUE THREAD

**Issue by RYOSKATE** [UnicoenProject/Junicoen#16]
XXX.g4ファイルを追加(、変更)すると
XXXBaseVisitor.java
XXXLexer.java
XXXParser.java
XXXVisitor.java
が自動的に生成されますが生成直後はファイルにエラーがあると表示されました。
`package net.unicoen.parser;`
をそれぞれに追記することでエラーを解消できました。

**Comment by junk0612** [comment]
どのようなファイルを追加されたかわかりませんが、

```
@header{
    package net.unicoen.parser;
}
```

を`.g4`の文法記述より前に追加すると解消できませんか？

**Comment by RYOSKATE** [comment]
解消できました。
